environment: "dev"
server:
  host: "localhost"
  port: "3000"
database:
  driver: "sqllite"
  db_url_secret_key: "coffeechat.db"
  db_name_secret_key: "local"
  aad_scope: ""
auth:
  jwt_secret: "local"
  token_expiry_minutes: 60
azure: # not used locally
  keyvaulturl: "https://develkeyvault.vault.azure.net"
  tnenat_id: ""
