environment: "dev"
server:
  host: "localhost"
  port: "3000"
database:
  type: "sqllite"
  db_url: "coffeechat.db"
  db_name: "local"
  scope: ""
auth:
  jwt_secret: "local"
  token_expiry_minutes: 60
azure: # not used locally
  keyvaulturl: "https://develkeyvault.vault.azure.net"
  tnenat_id: ""
