environment: "prod"
server:
  host: "0.0.0.0"
  port: "8080"
database:
  driver: "postgres"
  db_url_secret_key: "dbconnectionstring" # populated from keyvault
  db_name_secret_key: "dbcoffeechat" # populated from keyvault
  aad_scope: "https://ossrdbms-aad.database.windows.net//.default"
  ports: 5432
  db_user_secret_key: "postgresdbuser"
auth:
  jwt_secret: "coffeechat-jwt-signing-secret-prod" # populated from keyvault
  token_expiry_minutes: 30
azure:
  keyvaulturl: "https://develkeyvault.vault.azure.net"
  tenant_id: "" # populated from env var
